---
title: Rasterisation
runningheader: "Illustrating Raster Maps" # only for pdf output
subtitle: "Via Cycle Hire Capacity" # only for html output
author: notes
date: "`r Sys.Date()`"
bibliography: ../../bibliography/bibliography.bib
csl: ../../bibliography/cambridge-university-press-numeric.csl
urlcolor: olive
linkcolor: brown
citecolor: orange
link-citations: yes
classoption:
  - fleqn
extra_dependencies:
  - float
site: bookdown::bookdown_site
output:
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
    keep_tex: FALSE
    toc: FALSE
header-includes:
  - \usepackage{color}
  - \usepackage{caption}
  - \usepackage{bm}
  - \usepackage{booktabs}
  - \usepackage{xcolor}
  - \usepackage{titlesec}
  - \usepackage{tikz}
  - \usepackage{amsthm}
  - \usepackage{hyperref}
  - \usepackage[nameinlink, capitalize]{cleveref}
  - \usepackage[utf8]{inputenc}
  - \usepackage{ragged2e}
  - \usepackage{fancyhdr}
  - \usepackage{appendix}
  - \newtheorem{theorem}{Theorem}
  - \newtheorem{corollary}{Corollary}[theorem]
  - \newtheorem{proposition}{Proposition}[theorem]
  - \newtheorem{remark}{Remark}
  - \newtheorem{definition}{Definition}
  - \captionsetup[figure]{font={small, color=gray}, width=.8\linewidth}
  - \definecolor{darkgrey}{HTML}{4a4a4a}
  - \definecolor{duskyblue}{HTML}{6C779C}
  - \definecolor{wine}{rgb}{.44,.18,.21}
  - \definecolor{darkolive}{HTML}{546A2F}
  - \creflabelformat{equation}{#2\textup{#1}#3}
---



<!--- Global Settings --->
```{r include = FALSE}

# Settings
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = 'latex')
options(knitr.kable.NA = '')

# Invalidate cache when the tufte version changes
library(tufte)
knitr::opts_chunk$set(cache.extra = packageVersion(pkg = 'tufte'))
options(htmltools.dir.version = FALSE)
```


```{r include = FALSE}
library(xtable)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)

library(magrittr)
library(latex2exp)
library(patchwork)
library(knitr)
library(kableExtra)

```

<!--- settings --->
```{r exploration settings}
pathstr <- dirname(getwd())
```

<!--- functions --->
```{r exploration functions}
sys.source(file = file.path(pathstr, 'rasterisation', 'Raw.R'), envir = knitr::knit_global())
```

# The fundamentals

```{r}
raw <- Raw()
diagram <- raw$diagram
properties <- raw$properties
```

This example illustrates the Open Street Map (OSM) bicycle hire data. Its Geographic Co$\ddot{o}$rdinate System is `r properties$input`

```{r, fig.align = 'center'}
diagram
```
